import React, { useEffect, useState } from "react";
import {
    Text,
    View,
    StyleSheet,
    ScrollView,
    ActivityIndicator,
    ImageBackground
} from "react-native";

import theme from "../../constants/colors";
import { fontSizes, spacing, sizes } from "../../utils/fontSizes";
import { getGoldPrediction } from "../../api/goldApi";

const GoldPredictionScreen = () => {

    const [goldPrediction, setGoldPrediction] = useState({
        day: null,
        day10d: null,
        day30d: null,
    });

    const [loading, setLoading] = useState(true);

    useEffect(() => {

        const loadPredictions = async () => {

            try {

                const predictionDay = await getGoldPrediction("day");
                const prediction10 = await getGoldPrediction("10d");
                const prediction30 = await getGoldPrediction("30d");

                setGoldPrediction({
                    day: predictionDay.prediction,
                    day10d: prediction10.prediction,
                    day30d: prediction30.prediction,
                });

            } catch (e) {
                console.log("Prediction error", e);
            }

            setLoading(false);
        };

        loadPredictions();

    }, []);

    const getPredictionData = (value: number | null) => {

        if (value === null) return { label: "Loading...", color: theme.text.muted };

        if (value === 1) {
            return {
                label: "Price will RISE 📈",
                color: "#4AD39A"
            };
        }

        return {
            label: "Price will FALL 📉",
            color: "#FF6B6B"
        };
    };

    const day = getPredictionData(goldPrediction.day);
    const day10 = getPredictionData(goldPrediction.day10d);
    const day30 = getPredictionData(goldPrediction.day30d);

    return (

        <ScrollView style={styles.container} contentContainerStyle={{ paddingBottom: 40 }}>


            {/* MAIN CARD */}

            <ImageBackground
                source={require("../../assets/img/gradientBG2.jpg")}
                style={styles.mainCard}
                imageStyle={{ borderRadius: 20 }}
                resizeMode="stretch"
            >

                <Text style={styles.mainLabel}>Gold Price Prediction</Text>


                <Text style={styles.mainSub}>Forecast based on the most up-to-date gold data</Text>

            </ImageBackground>

            {/* SECTION */}

            <Text style={styles.sectionTitle}>How does this work?</Text>
            <Text style={styles.sectionSubtitle}>The algorithm has been analyzing the gold market every day since the early 2000s, learning to recognize price trends based on a wide range of factors that influence the global gold market.
            This prediction is generated by an AI model and should not be considered financial or investment advice.</Text>

            {/* PREDICTION CARDS */}

            <View style={styles.cardsContainer}>

                <View style={styles.card}>
                    <Text style={styles.cardTitle}>1 Day</Text>

                    {loading ? (
                        <ActivityIndicator color={theme.accent.magenta}/>
                    ) : (
                        <Text style={[styles.cardPrediction, { color: day.color }]}>
                            {day.label}
                        </Text>
                    )}

                    <Text style={styles.cardPredictionSubtitle}>The AI predicts gold price movement for the next 24 hours.
                        This is highly sensitive to daily market fluctuations, so short-term predictions can vary.
                        Use as an informative signal, not investment advice.</Text>
                </View>

                <View style={styles.card}>
                    <Text style={styles.cardTitle}>10 Days</Text>

                    {loading ? (
                        <ActivityIndicator color={theme.accent.magenta}/>
                    ) : (
                        <Text style={[styles.cardPrediction, { color: day10.color }]}>
                            {day10.label}
                        </Text>
                    )}

                    <Text style={styles.cardPredictionSubtitle}>
                    The 10-day prediction provides a broader view of market trends.
                        The model’s accuracy is around 60%, reflecting emerging patterns over the next two weeks.
                        For educational purposes only.
                    </Text>
                </View>

                <View style={styles.card}>
                    <Text style={styles.cardTitle}>30 Days</Text>

                    {loading ? (
                        <ActivityIndicator color={theme.accent.magenta}/>
                    ) : (
                        <Text style={[styles.cardPrediction, { color: day30.color }]}>
                            {day30.label}
                        </Text>
                    )}

                    <Text style={styles.cardPredictionSubtitle}>
                    The 30-day forecast identifies stronger trends in the gold market.
With more data to analyze, the model reaches approximately 65% accuracy.
This is not financial advice—use as guidance only.
                    </Text>
                </View>

            </View>

        </ScrollView>

    );
};

const styles = StyleSheet.create({

    container: {
        flex: 1,
        backgroundColor: theme.background.primary,
    },

    title: {
        paddingHorizontal: 20,
        paddingTop: 80,
        fontSize: fontSizes.h4,
        fontWeight: "bold",
        color: theme.text.primary,
        fontFamily: "ZalandoSansExpanded-Italic",
        marginBottom: 20,
    },

    cardPredictionSubtitle: {
        fontSize: fontSizes.caption,
        color: theme.text.muted,
        fontFamily: "ZalandoSansExpanded-Italic",
        marginBottom: spacing.lg,
        // paddingHorizontal: spacing.xl,
    },

    mainCard: {
        marginHorizontal: spacing.xl,
        borderRadius: sizes.cardBorderRadius,
        padding: spacing.xxl,
        alignItems: "center",
        marginTop: 80,
        marginBottom: spacing.xxl,
    },

    mainLabel: {
        fontSize: fontSizes.h4,
        fontWeight: "bold",
        color: "rgba(255, 255, 255)",
        fontFamily: "ZalandoSansExpanded-Italic",
        marginBottom: spacing.md,
    },

    mainPrediction: {
        fontSize: fontSizes.xlarge,
        fontWeight: "bold",
        fontFamily: "ZalandoSansExpanded-Italic",
        marginBottom: spacing.sm,
    },

    mainSub: {
        fontSize: fontSizes.caption,
        color: "rgba(255,255,255,0.7)",
        fontFamily: "ZalandoSansExpanded-Italic",
    },

    sectionTitle: {
        fontSize: fontSizes.h5,
        fontWeight: "bold",
        color: theme.text.primary,
        fontFamily: "ZalandoSansExpanded-Italic",
        marginBottom: spacing.lg,
        paddingHorizontal: spacing.xl,
    },

    cardsContainer: {
        paddingHorizontal: spacing.xl,
        gap: spacing.md,
        marginBottom: 100,
    },

    card: {
        backgroundColor: theme.background.secondary,
        borderRadius: sizes.cardBorderRadius,
        padding: sizes.cardPadding,
    },

    cardTitle: {
        fontSize: fontSizes.caption,
        color: theme.text.muted,
        fontFamily: "ZalandoSansExpanded-Italic",
        marginBottom: spacing.sm,
    },

    cardPrediction: {
        fontSize: fontSizes.h4,
        fontWeight: "bold",
        fontFamily: "ZalandoSansExpanded-Italic",
    },
    sectionSubtitle: {
        fontSize: fontSizes.caption,
        color: theme.text.muted,
        fontFamily: "ZalandoSansExpanded-Italic",
        marginBottom: spacing.lg,
        paddingHorizontal: spacing.xl,
    },
});

export default GoldPredictionScreen;